"""Business assumptions, in one place.

Every number here is an assumption, not a measurement. They are collected in a
single module so that a reviewer can change one value and re-run the whole
analysis, and so that no assumption is buried inside a query.

Olist is a marketplace: it does not keep the GMV of a sale, it keeps a
commission on it. Modelling margin on GMV would overstate the economics by
roughly an order of magnitude, so the unit economics here are built on the
commission line.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# Canonical Olist CSVs, mirrored on the Hugging Face Hub so the project is
# reproducible without Kaggle credentials.
DATA_SOURCE = "https://huggingface.co/datasets/aviahYadler/Olist_Ecommerce_Dataset/resolve/main"

OLIST_TABLES = (
    "olist_customers_dataset",
    "olist_orders_dataset",
    "olist_order_items_dataset",
    "olist_order_payments_dataset",
)


@dataclass(frozen=True)
class MarginAssumptions:
    """How GMV becomes contribution margin.

    take_rate
        Commission the marketplace charges the seller. Olist does not publish
        it; 15% is within the published range of Brazilian marketplaces and is
        the single most sensitive input in this model.
    psp_fee_rate
        Payment-processing cost, charged on the full transaction value rather
        than on the commission, which is why it is applied to GMV.
    variable_support_cost
        Per-order cost of service, disputes and reverse logistics.
    """

    take_rate: float = 0.15
    psp_fee_rate: float = 0.025
    variable_support_cost: float = 1.50


@dataclass(frozen=True)
class ChannelMix:
    """Simulated acquisition channels.

    SIMULATED. Olist publishes no acquisition-channel field and no media spend.
    Channel membership and spend are generated by this project so that the
    unit-economics machinery can be demonstrated end to end.

    Paid channels carry spend and therefore have a CAC. Unpaid channels carry
    none: their CAC is undefined, not zero, and the pipeline keeps it null
    rather than reporting a flattering infinity.
    """

    weights: dict[str, float] = field(
        default_factory=lambda: {
            "paid_search": 0.22,
            "paid_social": 0.18,
            "organic_search": 0.27,
            "direct": 0.15,
            "email_crm": 0.08,
            "marketplace_referral": 0.10,
        }
    )
    paid_channels: tuple[str, ...] = ("paid_search", "paid_social", "email_crm")

    # Share of the paid budget each paid channel receives.
    budget_share: dict[str, float] = field(
        default_factory=lambda: {
            "paid_search": 0.54,
            "paid_social": 0.40,
            "email_crm": 0.06,
        }
    )
    # Total paid budget is set as a share of the PREVIOUS month's net revenue.
    # Two reasons for the lag: it is how budgets are actually planned, and it
    # removes any same-period link between spend and the outcome being measured.
    marketing_intensity: float = 0.25
    budget_noise_sd: float = 0.12
    seed: int = 20261002


# Olist barely operated before 2017: 2016-09 and 2016-12 contain a single order
# each, and 2016-10 is a partial launch month. Including them would produce CAC
# figures in the thousands that say nothing about acquisition efficiency.
#
# BUDGET_BASE_START is where the revenue curve that sizes the budget begins.
# ANALYSIS_START is one month later, because a budget built on the previous
# month's revenue cannot exist for the first month of the series.
BUDGET_BASE_START = "2017-01"
ANALYSIS_START = "2017-02"
ANALYSIS_END = "2018-08"


MARGIN = MarginAssumptions()
CHANNELS = ChannelMix()
